djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name="signup"),
    path('password-reset', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views 
app_name = "leads"

urlpatterns = [
    path('', views.LeadListView.as_view() , name='lead-list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/category-update/', views.LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path('<int:pk>/assign-agent',views.AssignAgentView.as_view(), name="assign-agent"),
    path('create/', views.LeadCreateView.as_view(), name="lead-create"),
    path('categories/', views.CategoryListView.as_view(),name="category-list"),
    path('categories/create/', views.CategoryCreateView .as_view(), name="category-create"),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(),name="category-detail"),
    path('categories/<int:pk>/update', views.CategoryUpdateView.as_view(),name="category-update"),
    path('categories/<int:pk>/delete', views.CategoryDeleteView.as_view(),name="category-delete"),

]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_organiser = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email
    
class Category(models.Model): 
    name = models.CharField(max_length=30) # New, Contacted, Coverted, Unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(Agent, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField() 

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

def post_user_created_signal(sender, instance, created, **kwgrs):
    if created:
        UserProfile.objects.create(user=instance)
        print(instance, created)

post_save.connect(post_user_created_signal,sender=User)
    

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Agent, Category

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number',
            'email',
        )
       

class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age  = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

class AgentAssignForm(forms.Form):
    agent = forms.ModelChoiceField(
        queryset=Agent.objects.none()
    )
    
    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AgentAssignForm,self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ( 'name', )

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Lead, Category
from .forms import (
LeadModelForm, 
CustomUserCreationForm, 
AgentAssignForm, 
LeadCategoryUpdateForm,
CategoryForm,
) 
from agents.mixins import OrganiserAndLoginRequiredMixin

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    def get_success_url(self) -> str:
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user) 
        return queryset
    
    def get_context_data(self, **kwargs):
        user = self.request.user 
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile, agent__isnull=True)
            context.update(
                {"unassigned_leads": queryset}
            )
        return context

class LeadDetailView(OrganiserAndLoginRequiredMixin,generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset

class LeadCreateView(OrganiserAndLoginRequiredMixin,generic.CreateView):
    template_name ="leads/lead_create.html"
    form_class = LeadModelForm
    def get_success_url(self) -> str:
        return reverse("leads:lead-list")
    
    def form_valid(self, form: LeadModelForm):
        lead_organisation = self.request.user.userprofile 
        lead = form.save(commit=False)
        lead.organisation = lead_organisation
        lead.save()
        send_mail(
            subject="A lead has been created",
            message="Go to the side to see the new lead",
            from_email="localDjangoEmail@noreply.com",
            recipient_list=["faiz.kadir.ismail@gmail.com"]
        )
        return super(LeadCreateView, self).form_valid(form)
  
class LeadUpdateView(OrganiserAndLoginRequiredMixin,generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_success_url(self) -> str:
        return reverse("leads:lead-list")
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)
    
class LeadDeleteView(LoginRequiredMixin,generic.DeleteView):
    template_name = "leads/lead_delete.html"
    def get_success_url(self) -> str:
        return reverse("leads:lead-list")
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)

class AssignAgentView(OrganiserAndLoginRequiredMixin,generic.FormView):
    template_name="leads/assign_agent.html"
    form_class=AgentAssignForm

    def get_form_kwargs(self, **kwargs):
        kwargs =super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update(
        {
            "request": self.request
        }
        )
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

class CategoryListView(LoginRequiredMixin,generic.ListView):
    template_name = "leads/category_list.html"
    context_object_name = "categories"
    

    def get_context_data(self, **kwargs) :
        user = self.request.user
        context = super(CategoryListView, self).get_context_data(**kwargs)
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)

        context.update(
            {
                "unassigned_lead_count": queryset.filter(category__isnull=True).count()
            }
        )
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)
        return queryset
    
class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        leads = self.get_object().leads.all()
        context.update(
            {
                "leads": leads
            }
        )
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)
        return queryset
    
class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_success_url(self) -> str:
        return reverse("leads:lead-detail", kwargs={"pk":self.get_object().id})
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset
    
class CategoryCreateView(OrganiserAndLoginRequiredMixin,generic.CreateView):
    template_name ="leads/category_create.html"
    form_class = CategoryForm
    def get_success_url(self) -> str:
        return reverse("leads:category-list")
    
    def form_valid(self, form: LeadModelForm):
        category_organisation = self.request.user.userprofile 
        category = form.save(commit=False)
        category.organisation = category_organisation
        category.save()
        return super(CategoryCreateView, self).form_valid(form)

class CategoryUpdateView(OrganiserAndLoginRequiredMixin,generic.UpdateView):
    template_name ="leads/category_update.html"
    form_class = CategoryForm
    def get_success_url(self) -> str:
        return reverse("leads:category-list")
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organiser:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset

class CategoryDeleteView(LoginRequiredMixin,generic.DeleteView):
    template_name = "leads/category_delete.html"
    def get_success_url(self) -> str:
        return reverse("leads:category-list")
    
    def get_queryset(self):
        user = self.request.user
        return Category.objects.filter(organisation=user.userprofile)

def lead_list(request):
    leads = Lead.objects.all()
    
    context = {
        "leads" : leads
    }
        
    return render(request, "leads/lead_list.html", context)

def lead_detail(request, pk):   
    lead = Lead.objects.get(id=pk)
    context = {
        "lead":lead
    }
    return render(request, 'leads/lead_detail.html', context)

def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)

def lead_update(request,pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "lead": lead,
        "form" : form ,
    }
    return render(request, 'leads/lead_update.html', context)

def lead_delete(request,pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")

leads/templates/leads/assign_agent.html
{% extends 'base.html' %}
{% load  tailwind_filters %}
{% block content  %}

<div class="container px-5 py-5 mx-auto">
    <div class="flex flex-col w-full mb-12">   
     <div class="max-w-lg max-auto container px-5 py-1 mx-auto">
        <h1>Assign Agent</h1>
        <a href="{% url 'leads:lead-list' %}"><p class="text-sm hover:text-blue-500 mb-4">Go back to leads</p></a>
        <hr>
        <form method="post" action="" class="mt-5">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="w-full text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
        </form>   
     </div>
    </div>
</div>



{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-10 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-t border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-900">Category</h1>
                <div>
                    {% if request.user.is_organiser %}
                    <a class="text=text-gray-600 hover:text-blue-500 " href="{% url 'leads:category-create' %}">Create
                        Category</a>
                    {% endif %}

                </div>
            </div>
        </div>

        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Lead Count</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Edit</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="px-4 py-3">Unassigned</td>
                        <td class="px-4 py-3">{{unassigned_lead_count}}</td>
                    </tr>
                    {% for category in categories %}
                    <tr>
                        <td class="px-4 py-3">
                            <a href="{% url 'leads:category-detail' category.pk %}">{{category.name}}</a>
                        </td>
                        <td class="px-4 py-3">{{category.leads.count}}</td>
                        <td class="px-4 py-3">
                            <a href="{% url 'leads:category-update' category.pk %}" class="">
                                <svg class="h-5 w-5 text-indigo-500" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                </svg>

                            </a>
                        </td>
                        <td class="px-4 py-3">
                            <a href="{% url 'leads:category-delete' category.pk %}" class="">
                                <svg class="h-5 w-5 text-indigo-500" viewBox="0 0 24 24" fill="none"
                                    stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <polyline points="3 6 5 6 21 6" />
                                    <path
                                        d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                                    <line x1="10" y1="11" x2="10" y2="17" />
                                    <line x1="14" y1="11" x2="14" y2="17" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
</section>
{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead-detail' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                    <!-- active -->
                    <a href="{% url 'leads:lead-category-update' lead.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'leads:lead-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <form method="post" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="w-1/2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded w-full">Submit</button>
                </form>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="{% static 'images/crm-corp-img.jpeg'%}">
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <!-- active -->
                    <a href="{% url 'leads:lead-detail' lead.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
                    <a href="{% url 'leads:lead-category-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'leads:lead-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <p class="leading-relaxed mb-4">{{lead.description}}</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{lead.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Phone Number</span>
                    <span class="ml-auto text-gray-900">{{lead.phone_number}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{lead.email}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Agent</span>
                    <span class="ml-auto text-gray-900">{{lead.agent}}</span>
                </div>
                <div class="">
                    <div class="py-5 border-t border-gray-200 w-full">
                        <a href="{% url 'leads:lead-delete' lead.pk %}"
                            class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</a>
                    </div>
                </div>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="{% static 'images/crm-corp-img.jpeg'%}">
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-10 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-t border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-900">Leads</h1>
                <div>
                    <a class="text=text-gray-600 hover:text-blue-500 " href="{% url 'leads:category-list' %}">View
                        Categories</a>
                </div>
            </div>
            {% if request.user.is_organiser %}
            <div>
                <a class="text=text-gray-600 hover:text-blue-500 " href="{% url 'leads:lead-create' %}">Create Leads</a>
            </div>
            {% endif %}
        </div>

        <!-- Assigned Leads -->
        <div class="container px-5 py-5 mx-auto">
            <div class="lg:w-2/3 w-full mx-auto overflow-auto">
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                        <tr>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                                First Name</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                Last Name</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                Description</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                Category</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                View</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                        <tr>
                            <td class="px-4 py-3">{{lead.first_name}}</td>
                            <td class="px-4 py-3">{{lead.last_name}}</td>
                            <td class="px-4 py-3">{{lead.description|truncatechars:50 }}</td>
                            <td class="px-4 py-3">
                                {% if lead.category.name == "Contacted" %}
                                <span
                                    class="bg-gray-500 font-bold text-gray-800 text-center py-1 px-2 text-xs rounded">{{lead.category}}</span>
                                {% elif lead.category.name == "Converted" %}
                                <span
                                    class="bg-green-400 font-bold text-gray-800 text-center py-1 px-2 text-xs rounded">{{lead.category}}</span>
                                {% elif lead.category.name == "Unconverted" %}
                                <span
                                    class="bg-red-500 font-bold text-gray-800 text-center py-1 px-2 text-xs rounded">{{lead.category}}</span>
                                {% else %}
                                <span
                                    class="bg-yellow-500 font-bold text-gray-800 text-center py-1 px-2 text-xs rounded">Unassigned</span>
                                {% endif %}

                            </td>
                            <td class="px-4 py-3">
                                <a href="{% url 'leads:lead-detail' lead.pk %}">
                                    <svg class="h-6 w-6 text-indigo-500" width="24" height="24" viewBox="0 0 24 24"
                                        stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                                        stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" />
                                        <circle cx="10" cy="10" r="7" />
                                        <line x1="7" y1="10" x2="13" y2="10" />
                                        <line x1="10" y1="7" x2="10" y2="13" />
                                        <line x1="21" y1="21" x2="15" y2="15" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <p>There are currently no leads</p>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- Unassigned Leads -->
        {% if unassigned_leads.exists %}
        <div class="container px-5 py-5 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Unassigned Leads</h1>
                <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Please assign these leads to available agents
                </p>
            </div>
            <div class="lg:w-2/3 w-full mx-auto overflow-auto">
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                        <tr>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                                First Name</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                Last Name</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                Description</th>
                            <th
                                class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                                Assignment</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in unassigned_leads %}
                        <tr>
                            <td class="px-4 py-3">{{lead.first_name}}</td>
                            <td class="px-4 py-3">{{lead.last_name}}</td>
                            <td class="px-4 py-3">{{lead.description|truncatechars:255 }}</td>
                            <td class="px-4 py-3"><a href="{% url 'leads:assign-agent' lead.pk %}">Assign</a></td>
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}