agents/urls.py
from django.urls import path
from . import views

app_name="agents"

urlpatterns = [
    path('', views.AgentListView.as_view(), name='agent-list'),
    path('create/', views.AgentCreateView.as_view(), name='agent-create' ),
    path('<int:pk>/', views.AgentDetailView.as_view(), name='agent-detail'),
    # path('<int:pk>/update/', views.AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', views.AgentDeleteView.as_view(), name='agent-delete'),
    path('<int:pk>/update/', views.AgentUserUpdateView, name='agent-update'),
    path('<int:pk>/leads/', views.AgentLeadListView.as_view(), name='agent-lead-list' )
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name="signup"),
    path('password-reset', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

class AgentUserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields ={
            'email',
            'first_name',
            'last_name',
            'username',
        }

        field_order = ['email','first_name','last_name', 'username',]

agents/views.py
from django.views import generic
from django.shortcuts import reverse, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent, User, Lead
from .forms import AgentModelForm, AgentUserUpdateForm
from .mixins import OrganiserAndLoginRequiredMixin
from django.core.mail import send_mail
import random

class AgentListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"
    context_object_name = "agents"
    
    def get_queryset(self) :
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

class AgentLeadListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_lead_list.html"
    context_object_name = "agent_leads"

    def get_queryset(self) :
        organisation = self.request.user.userprofile
        leads = Lead.objects.filter(organisation=organisation, agent__id=self.kwargs["pk"])
        print(leads)
        return leads
    
    def get_context_data(self, **kwargs):
        context = super(AgentLeadListView, self).get_context_data(**kwargs)
        queryset = Agent.objects.get(organisation=self.request.user.userprofile, id=self.kwargs["pk"])
        context.update(
            { "agent": queryset}
        )
        return context


    
class AgentCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm
    # overide the default function of the class
    def get_success_url(self) -> str:
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organiser = False
        user.set_password(f"{random.randint(0,1000000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation = self.request.user.userprofile
        )
        send_mail(
            subject="You are invited to be an Agent",
            message="You were added to be an agent on DJCRM. Please come and start working",
            from_email="djcrm@gmail.com",
            recipient_list=["agentoso@gmail.com"]
        )

        # agent.organisation = self.request.user.userprofile
        # agent.save()
        return super(AgentCreateView,self).form_valid(form)

class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)    
    
class AgentUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class =  AgentModelForm
    # overide the default function of the class
    
    def get_success_url(self) -> str:
        return reverse("agents:agent-detail", kwargs={"pk":self.get_object().id})
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        # return Agent.objects.filter(organisation=organisation)
        # user = User.objects.filter(agent__id=self.kwargs["pk"])
        print(Agent.objects.filter(user__id=self.kwargs["pk"]))
        return Agent.objects.filter(user__id=self.kwargs["pk"])
    
class AgentDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
    def get_success_url(self):
        return reverse("agents:agent-list")
    

#TODO: Decorative filter for login users only
def AgentUserUpdateView(request, pk):
    user = User.objects.get(agent__id=pk)
    agent = Agent.objects.get(id=pk,organisation=request.user.userprofile)
    form = AgentUserUpdateForm(instance=user)
    if request.method == "POST":
        form = AgentUserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('agents:agent-list')
    context = {
    "user": user,
    "form" : form,
    "agent" : agent,
    }
    return render(request, 'agents/agent_update.html',context)
   

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content  %}


<div class="container px-5 py-5 mx-auto">
    <div class="flex flex-col w-full mb-12">   
     <div class="max-w-lg max-auto container px-5 py-1 mx-auto">
        <h1>Create A New Agent</h1>
        <a href="{% url 'agents:agent-list' %}"><p class="text-sm hover:text-blue-500 mb-4">Go back to agents</p></a>
        <hr>
        <form method="post" action="" class="mt-5">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="w-full text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
        </form>   
     </div>
    </div>
</div>


{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="container px-5 py-5 mx-auto">
    <div class="flex flex-col w-full mb-12">   
     <div class="max-w-lg max-auto container px-5 py-1 mx-auto">
        <h1>Are you sure you want to delete this agent: {{agent.user.first_name}} {{agent.user.last_name }}?</h1>
        <a href="{% url 'agents:agent-list' %}"><p class="text-sm hover:text-blue-500 mb-4">Go back to agents</p></a>
        <hr>
        <form method="post" action="" class="mt-5">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="w-full text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
        </form>   
     </div>
    </div>
</div>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.first_name}} {{agent.user.last_name}}
                </h1>
                <div class="flex mb-4">
                    <!-- active -->
                    <a href="{% url 'agents:agent-detail' agent.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
                    <a href="{% url 'agents:agent-lead-list' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Leads</a>

                    <a href="{% url 'agents:agent-update' agent.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <p class="leading-relaxed mb-4">TODO: Desc</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Name</span>
                    <span class="ml-auto text-gray-900">{{agent.user.first_name}} {{agent.user.last_name}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Username</span>
                    <span class="ml-auto text-gray-900">{{agent.user.username}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{agent.user.email}}</span>
                </div>
                <div class="">
                    <a href="{% url 'agents:agent-delete' agent.pk %}"
                    class="w-1/2 ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</a>
                </div>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/agent_lead_list.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT's LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.first_name}}
                    {{agent.user.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:agent-detail' agent.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                    <!-- active -->
                    <a href="{% url 'agents:agent-lead-list' agent.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Leads</a>

                    <a href="{% url 'agents:agent-update' agent.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <!-- list start -->
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                        <tr>
                          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
                          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>                 
                          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">View</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for lead in agent_leads %}
                        <tr>
                            <td>{{lead.first_name}}</td>
                            <td>{{lead.last_name}}</td>
                            <td>TODO link</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                </table>
                <!-- list end -->
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
    </div>
</section>



{% endblock content %}

agents/templates/agents/agent_list.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-10 mx-auto">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-t border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-900">Agents</h1>
            </div>
            {% if request.user.is_organiser %}
            <div>
                <a class="text=text-gray-600 hover:text-blue-500 " href="{% url 'agents:agent-create' %}">Create
                    Agents</a>
            </div>
            {% endif %}
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            First Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Last Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Email</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Username</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            View</th>

                    </tr>
                </thead>
                <tbody>
                    {% for agent in agents %}
                    <tr>
                        <td class="px-4 py-3">{{agent.user.first_name}} </td>
                        <td class="px-4 py-3">{{agent.user.last_name}}</td>
                        <td class="px-4 py-3">{{agent.user.email}}</td>
                        <td class="px-4 py-3">{{agent.user.username}}</td>
                        <td class="px-4 py-3">
                            <a href="{% url 'agents:agent-detail' agent.pk %}">
                                <svg class="h-6 w-6 text-indigo-500" width="24" height="24" viewBox="0 0 24 24"
                                    stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" />
                                    <circle cx="10" cy="10" r="7" />
                                    <line x1="7" y1="10" x2="13" y2="10" />
                                    <line x1="10" y1="7" x2="10" y2="13" />
                                    <line x1="21" y1="21" x2="15" y2="15" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <p>There are no agent</p>
                    {% endfor%}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.first_name}} {{agent.user.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                    <a href="{% url 'agents:agent-lead-list' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Leads</a>
                    <!-- active -->
                    <a href="{% url 'agents:agent-update' agent.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update Details</a>
                </div>
                <form method="post" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="w-1/2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded w-full">Submit</button>
                </form>         
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/archived_agent_list.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-t border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-900">Agents</h1>
            </div>
            <div>
                <a class="text=text-gray-600 hover:text-blue-500 " href="{% url 'agents:agent-create' %}">Create Agents</a>
            </div>

        </div>
        <div class="flex flex-wrap -m-4">
            {% for agent in agents %}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div
                        class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                            {{agent.user.first_name}} {{agent.user.last_name}}
                        </h2>
                        <p class="leading-relaxed text-base">
                            Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                            taxidermy. Gastropub indxgo juice poutine.
                        </p>
                        <a href="{% url 'agents:agent-detail' agent.pk %}"
                            class="mt-3 text-indigo-500 inline-flex items-center">View This Agent
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}